[package]
name = "svep"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12.0"
winit = "0.26.1"
cgmath = "0.18.0"
env_logger = "0.9.0"
pollster = "0.2.5"
rand = "0.8.4"
bytemuck = { version = "1.7.3", features = [ "derive" ] }