[package]
name = "svep"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6.0"
env_logger = "0.9.0"
rand = "0.8.4"
lazy_static = "1.4.0"
noise = "0.7.0"
num_cpus = "1.13.1"
threadpool = "1.8.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3